apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-menu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-menu
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: food-menu
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
        - image: vilrons/kuber-test-app:latest
          name: ramen
          ports:
            - containerPort: 7777
          env:
            - name: POD_NAME
              value: ramen
            - name: FLASK_PORT
              value: '7777'
            - name: FLASK_HOST
              value: 0.0.0.0
        - image: vilrons/kuber-test-app:latest
          name: sushi
          ports:
            - containerPort: 8888
          env:
            - name: POD_NAME
              value: sushi
            - name: FLASK_PORT
              value: '8888'
            - name: FLASK_HOST
              value: 0.0.0.0
        - image: vilrons/kuber-test-app:latest
          name: tempura
          ports:
            - containerPort: 9999
          env:
            - name: tempura
              value: tempura
            - name: FLASK_PORT
              value: '9999'
            - name: FLASK_HOST
              value: 0.0.0.0
