apiVersion: v1
kind: Service
metadata:
  name: food-menu
spec:
  selector:
    app: food-menu
  ports:
  - protocol: TCP
    port: 1234
    targetPort: 7777
    name: ramen
  - protocol: TCP
    port: 1235
    targetPort: 8888
    name: sushi
  - protocol: TCP
    port: 1236
    targetPort: 9999
    name: tempura
  - protocol: TCP
    port: 8080
    targetPort: 80
    name: nginx
