apiVersion: v1
kind: Pod
metadata:
  name: food-menu-test
spec:
  containers:
  - name: sushi
    image: ubuntu:jammy-20240111
    command: ["sh", "-c"]
    args:
    - |
      apt-get update
      apt-get install -y curl vim iputils-ping dnsutils lsof
      sleep 10
      curl http://food-menu:1234/pod
      sleep 3600
  - name: nginx-test
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
    - |
      sleep 10
      wget -O - food-menu:8080
      sleep 3600
